version: '3.8'

services:
  bucket-app:
    build: ./
    command: ./bucket-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: telebot_postgres
    image: postgres:14
    restart: always
    env_file:
      - ./.env
    ports:
      - "5436:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
